services:
  echoserver:
    build: { context: echoserver }
    environment: { ECHOSERVER_LISTEN: "0.0.0.0:8000" }
    ports: ["8000:8000"]
    develop:
      watch:
        - { action: rebuild, path: ./echoserver }
